---
- name: "ensure ansible's apt_repository dependency is installed"
  apt: pkg=python-apt state=latest update_cache=true

- name: ensure nginx apt repository is up to date
  apt_repository: repo='ppa:nginx/stable'

- name: ensure nginx latest stable is installed
  apt: pkg=nginx state=latest update_cache=true
  notify:
    - restart nginx

- name: ensure the default site is removed
  file: path=/etc/nginx/sites-{{ item }}/default state=absent
  with_items:
    - enabled
    - available
  notify:
    - restart nginx

- name: ensure sites-available is configured
  template: src=nginx_sites-available.j2 dest=/etc/nginx/sites-available/{{ nginx_upstream_name }} group=root owner=root
  notify:
    - reload nginx

- name: ensure sites-available is symlinked to sites-enabled
  file: src=/etc/nginx/sites-available/{{ nginx_upstream_name }} dest=/etc/nginx/sites-enabled/{{ nginx_upstream_name }} state=link
  notify:
    - restart nginx

- name: ensure nginx starts on a fresh reboot
  service: name=nginx state=started enabled=yes